// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzA1rGdccsw4UJ6vob2Z1yDODvdFu5T9o',
    appId: '1:1019574153801:web:c52ca441d1681548848598',
    messagingSenderId: '1019574153801',
    projectId: 'fruits-hub-94e86',
    authDomain: 'fruits-hub-94e86.firebaseapp.com',
    storageBucket: 'fruits-hub-94e86.firebasestorage.app',
    measurementId: 'G-FM7MQR600S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ3M1ImqhlhQYThi0zt9W1A3pTDsd1Spk',
    appId: '1:1019574153801:android:c17cf40f52c3ff60848598',
    messagingSenderId: '1019574153801',
    projectId: 'fruits-hub-94e86',
    storageBucket: 'fruits-hub-94e86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVVfsKddLeCp_7iGJ2o--ZsSLEs4NBDi4',
    appId: '1:1019574153801:ios:07673133f2f9f1a5848598',
    messagingSenderId: '1019574153801',
    projectId: 'fruits-hub-94e86',
    storageBucket: 'fruits-hub-94e86.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVVfsKddLeCp_7iGJ2o--ZsSLEs4NBDi4',
    appId: '1:1019574153801:ios:07673133f2f9f1a5848598',
    messagingSenderId: '1019574153801',
    projectId: 'fruits-hub-94e86',
    storageBucket: 'fruits-hub-94e86.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzA1rGdccsw4UJ6vob2Z1yDODvdFu5T9o',
    appId: '1:1019574153801:web:82541ef374f83653848598',
    messagingSenderId: '1019574153801',
    projectId: 'fruits-hub-94e86',
    authDomain: 'fruits-hub-94e86.firebaseapp.com',
    storageBucket: 'fruits-hub-94e86.firebasestorage.app',
    measurementId: 'G-JZJN5Y4G3Z',
  );
}
